### ISSUE TITLE
When I run secret-bridge nothing happens

### ISSUE THREAD

**Issue by NiyiOdumosu** [duo-labs/secret-bridge#9]
Hello, 

I've ran secret-bridge on my machine a few times but when I am expecting to see the detectors (primarily detect-secrets) catch my secret and print some results to the console nothing happens.

Below is my config.toml

```toml
detectors = [
    "detect-secrets",
    "git-secrets",
    "trufflehog"
]
[auth]
access_token=$GITHUB_TOKEN

[monitors]
    organizations = ['Hearst-Hatchery']
    users = ['NiyiOdumosu']
    repos = [niyi-test]

[webhook]
    secret=""
    host="0.0.0.0"

[notifiers.console]

[notifiers.slack_webhook]
    webhook_url=''
```
I ran `docker run -ti --rm -e GITHUB_WATCHER_TOKEN=$GITHUB_TOKEN duolabs/secret-bridge poll` and then I tried testing it by pushing up a fake secret key that has a high entropy string in the README in my `niyi-test` repo in github. 

I did not see anything happen in the console. I wanted to see a result in the console before configuring it with slack. Any idea why this is not working? the Github token is valid. I've used this token for various scripts and integrations before.

Any idea why the polling script is not picking up new git pushes to this repository?
